// --------- BEGIN RUNBOX LICENSE ---------
// Copyright (C) 2016-2019 Runbox Solutions AS (runbox.com).
//
// This file is part of Runbox 7.
//
// Runbox 7 is free software: You can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// Runbox 7 is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Runbox 7. If not, see <https://www.gnu.org/licenses/>.
// ---------- END RUNBOX LICENSE ----------

import * as moment from 'moment';

export enum EntryType {
    BUILD,
    CI,
    DOCS,
    FEAT,
    FIX,
    PERF,
    REFACTOR,
    STYLE,
    TEST
}

const typeMapping = {
    'build':    EntryType.BUILD,
    'ci':       EntryType.CI,
    'docs':     EntryType.DOCS,
    'feat':     EntryType.FEAT,
    'fix':      EntryType.FIX,
    'perf':     EntryType.PERF,
    'refactor': EntryType.REFACTOR,
    'style':    EntryType.STYLE,
    'test':     EntryType.TEST
};

export class ChangelogEntry {
    public datetime: moment.Moment;

    constructor(
        public hash:        string,
               datetime:    number,
        public type:        EntryType,
        public component:   string,
        public description: string,
    ) {
        this.datetime = moment(datetime * 1000); // in ms
    }

    get url(): string {
        return `https://github.com/runbox/runbox7/commit/${this.hash}`;
    }
}


// These entries are auto-generated from build-changelog.js.
// Manual edits will be overwritten.
// tslint:disable:quotemark
// BEGIN:AUTOGENERATED
const changes = [
    [
        "34cdcb9",
        "1579539932",
        "feat",
        "changelog",
        "Add a built-in changelog"
    ],
    [
        "444da1f",
        "1579000304",
        "style",
        "payment",
        "Make layout more responsive, add button color, and credit card logos."
    ],
    [
        "631cf19",
        "1578768357",
        "fix",
        "auth",
        "dont use type=\"number\" otherwise the form wont get the values"
    ],
    [
        "4f250b7",
        "1578578284",
        "fix",
        "account",
        "Improve error handling in bitpay payment dialog"
    ],
    [
        "8c3a898",
        "1578576969",
        "fix",
        "account",
        "disallow renewal of trial"
    ],
    [
        "3a4f561",
        "1577795829",
        "perf",
        "app",
        "lazy-load non-core modules to improve load times"
    ],
    [
        "d198c5d",
        "1576772266",
        "build",
        "deps",
        "Update webdriver-manager for new chromium versions"
    ],
    [
        "c269a66",
        "1576771367",
        "fix",
        "contacts",
        "Make the address form display correctly"
    ],
    [
        "efe52cc",
        "1576683344",
        "style",
        "print",
        "Add tooltip about printing vs the environment."
    ],
    [
        "d2fb368",
        "1576290169",
        "fix",
        "identities",
        "fix lint problems"
    ],
    [
        "a31c6da",
        "1576285439",
        "feat",
        "identities",
        "added more endpoints related to compose in mockserver"
    ],
    [
        "80308c8",
        "1576280267",
        "fix",
        "identities",
        "import Observable from rxjs instead of rxjs/Rx"
    ],
    [
        "73f305e",
        "1576274850",
        "fix",
        "idenitites",
        "update app.module and profile.module so e2e tests pass"
    ],
    [
        "add4d81",
        "1576264677",
        "fix",
        "identities",
        "move dependencies from app.module into profiles.module"
    ],
    [
        "a9a34cc",
        "1576176865",
        "fix",
        "identities",
        "add missing DevModule to app.module.ts"
    ],
    [
        "717bcc5",
        "1576175997",
        "fix",
        "identities",
        "import profiles module in app module"
    ],
    [
        "1b378ea",
        "1576174438",
        "fix",
        "identities",
        "add a type to data attribute"
    ],
    [
        "9161818",
        "1576172204",
        "fix",
        "identities",
        "return of to always return an observable via this method"
    ],
    [
        "0ac0868",
        "1576155138",
        "fix",
        "identities",
        "add Observable to load"
    ],
    [
        "9ae2eb1",
        "1576153002",
        "fix",
        "identities",
        "re-add required components to NgModule"
    ],
    [
        "37f9795",
        "1576089025",
        "fix",
        "idenitties",
        "fixed more review points and lint problems"
    ],
    [
        "bbfa515",
        "1576088885",
        "fix",
        "identities",
        "re-added these lines because it does not work without them here it seems"
    ],
    [
        "dee23f6",
        "1575961718",
        "fix",
        "travis",
        "fix travis errors"
    ],
    [
        "2377251",
        "1575957116",
        "fix",
        "profiles",
        "fix lint and merge review suggestions"
    ],
    [
        "d14169f",
        "1575955120",
        "fix",
        "appmodule",
        "removed unecessary imports from app.module.ts"
    ],
    [
        "334bc24",
        "1575953558",
        "fix",
        "lint",
        "identities lint problems fix"
    ],
    [
        "4fa195c",
        "1575750346",
        "fix",
        "compose",
        "use profiles signature"
    ],
    [
        "c7b377f",
        "1575747126",
        "fix",
        "profiles",
        "fixing profiles to compile"
    ],
    [
        "265e0d1",
        "1575742830",
        "feat",
        "identities",
        "identities"
    ],
    [
        "0ff194d",
        "1575633683",
        "build",
        "deps",
        "Update some dependencies"
    ],
    [
        "a5db0d3",
        "1575633175",
        "feat",
        "account",
        "Add a page for Paypal billing agreements"
    ],
    [
        "66c34c8",
        "1575632503",
        "feat",
        "account",
        "Allow enabling/disabling product autorenewal"
    ],
    [
        "e2db28d",
        "1575564524",
        "style",
        "intro",
        "Update introductory welcome text."
    ],
    [
        "7e07ab8",
        "1575383249",
        "style",
        "payments",
        "Keep the ZIP field underline from overflowing the form"
    ],
    [
        "f6c1bcb",
        "1575381183",
        "fix",
        "payments",
        "Improve error reporting for Stripe in some edge cases"
    ],
    [
        "1ac674f",
        "1575311869",
        "fix",
        "canvastable",
        "Keep columns from overlapping in the wrapped view"
    ],
    [
        "7f69e8e",
        "1575307453",
        "refactor",
        "rmmapi",
        "Switch to the new, faster REST endpoint for moving messages"
    ],
    [
        "80760d6",
        "1575283863",
        "style",
        "account",
        "Fix wording on the subscription page"
    ],
    [
        "7329b9a",
        "1575283389",
        "fix",
        "dkim",
        "add missing dot in dkim page > dns zone file"
    ],
    [
        "8fc3b16",
        "1575116953",
        "fix",
        "folders",
        "Make folders show up on old versions of Edge"
    ],
    [
        "5abe9e9",
        "1575045336",
        "style",
        "canvastable",
        "Fix overflow and adjustment of column headers"
    ],
    [
        "f32c1da",
        "1575041177",
        "feat",
        "account-products",
        "Only allow one subscription order at a time"
    ],
    [
        "9896cdc",
        "1575036646",
        "fix",
        "calendar",
        "Don't try to import events when user cancelled it"
    ],
    [
        "54bb5ee",
        "1575034297",
        "feat",
        "account-app",
        "Offer a redirect back to rmm6 if stripe payment form fails to load"
    ],
    [
        "abb66e0",
        "1575031474",
        "style",
        "update-notifier",
        "Make the version wording a bit more understandable"
    ],
    [
        "b3cc2ba",
        "1575026468",
        "style",
        "login",
        "Improve layout of login area. Move progress bar to footer."
    ],
    [
        "2f21669",
        "1574958021",
        "fix",
        "canvastable",
        "Make sure column widths are remembered and respected"
    ],
    [
        "fe0693f",
        "1574956692",
        "refactor",
        "webmail",
        "remove unused column widths code from AppComponent"
    ],
    [
        "7a6e340",
        "1574950551",
        "fix",
        "canvastable",
        "Fix scrolling with keyboard bindings"
    ],
    [
        "abefe2c",
        "1574783071",
        "feat",
        "update-notifier",
        "Include build time in appData"
    ],
    [
        "e58d15b",
        "1574780568",
        "feat",
        "update-notifier",
        "Include commit hash in app update data"
    ],
    [
        "28606b5",
        "1574774285",
        "feat",
        "calendar",
        "add overview -- a new calendar view mode"
    ],
    [
        "c534aac",
        "1574683303",
        "fix",
        "contacts",
        "make sure no details are leftover when switching between contacts"
    ],
    [
        "4bf0200",
        "1574681860",
        "feat",
        "contacts",
        "Add a way to select (and delete) multiple contacts"
    ],
    [
        "0eed26c",
        "1574676741",
        "style",
        "contacts",
        "make each row in contacts editor a flexbox"
    ],
    [
        "edf51a4",
        "1574673994",
        "fix",
        "folderlist",
        "handle draft subfolders"
    ],
    [
        "76ba8c3",
        "1574673570",
        "docs",
        "contributing",
        "Update TOC"
    ],
    [
        "2b7a221",
        "1574487772",
        "style",
        "login",
        "Improve style of error message and make layout more consistent."
    ],
    [
        "cef7878",
        "1574430474",
        "fix",
        "login",
        "Re-add the specialized expired account error"
    ],
    [
        "1296ecb",
        "1574370845",
        "fix",
        "authguard",
        "don't push users out to login if they're merely expired"
    ],
    [
        "163d88f",
        "1574346008",
        "style",
        "webmail",
        "Hide nav submenu in mobile view"
    ],
    [
        "0b65c8f",
        "1574345196",
        "feat",
        "contacts",
        "Implement a basic mobile view for Contacts"
    ],
    [
        "84b6c47",
        "1574232330",
        "feat",
        "login",
        "include checkbox option to use legacy and stay logged in"
    ],
    [
        "0d6b92c",
        "1574198440",
        "fix",
        "login",
        "fix lint"
    ],
    [
        "a746eb5",
        "1574177409",
        "fix",
        "dkim",
        "Change \"CNAME in DNS\"\", \"Active\" selector2 active date."
    ],
    [
        "32525ff",
        "1574092979",
        "fix",
        "login",
        "use this.handleLoginError in handleLoginResponse"
    ],
    [
        "89be95e",
        "1573947642",
        "fix",
        "login",
        "simplify login error messages"
    ],
    [
        "be9520b",
        "1573928680",
        "build",
        "dependencies",
        "update package-lock.json"
    ],
    [
        "a37257e",
        "1573928646",
        "fix",
        "Unit",
        "folderlist.component.spec.ts mock for hotkeys added"
    ],
    [
        "64ec6f4",
        "1573924677",
        "feat",
        "HomePage",
        "Add keyboard shortcuts"
    ],
    [
        "8026cf1",
        "1573924645",
        "feat",
        "HomePage",
        "Add keyboard shortcuts"
    ],
    [
        "f69af60",
        "1573848492",
        "style",
        "webmail",
        "Omit \"Deleting...\" feedback message when deleting messages."
    ],
    [
        "f58b874",
        "1573825263",
        "refactor",
        "authguard",
        "Add a fast pass for previously logged in users"
    ],
    [
        "c1fe23e",
        "1573800457",
        "feat",
        "loginerrors",
        "render more login errors"
    ],
    [
        "77aee54",
        "1573745308",
        "feat",
        "tests",
        "Add a ci-runner script and use it in Travis settings"
    ],
    [
        "e3506cb",
        "1573744450",
        "style",
        "menu",
        "Move the logout button to the \"global\" sidenav-menu"
    ],
    [
        "3171fb8",
        "1573669888",
        "style",
        "calendar",
        "make sure datepicker is usable in mobile view"
    ],
    [
        "0a861d0",
        "1573669866",
        "fix",
        "calendar",
        "make sure first-day-of-week settings are respected in event editor"
    ],
    [
        "40df944",
        "1573668248",
        "style",
        "calendar",
        "Make the calendar header more concise in mobile view"
    ],
    [
        "2d882ed",
        "1573665884",
        "style",
        "calendar",
        "Disable custom day template in mobile view"
    ],
    [
        "4abe522",
        "1573575906",
        "fix",
        "account-app",
        "Use ngOnInit consistently when loading async resources"
    ],
    [
        "c14aac7",
        "1573568860",
        "fix",
        "cart",
        "Don't perform async queries before the component is fully initialized"
    ],
    [
        "dfe49e1",
        "1573487344",
        "docs",
        "introductions",
        "Add links to more details about the project. (#348)"
    ],
    [
        "2e3be51",
        "1573486468",
        "feat",
        "menu",
        "Add buttons to navigate between calendar and webmail"
    ],
    [
        "85ea2fa",
        "1573478651",
        "fix",
        "tests",
        "Ensure that xapian is loaded in each testcase"
    ],
    [
        "d0ffd9d",
        "1573476255",
        "fix",
        "unit-tests",
        "Add MobileQueryService to test providers"
    ],
    [
        "3a53c4d",
        "1573475267",
        "fix",
        "contacts",
        "Cap the contacts buffer at 1 to prevent excessive memory usage"
    ],
    [
        "e0144a9",
        "1573475267",
        "fix",
        "contacts",
        "Prevent contact-details from reloading every time contact list reloads"
    ],
    [
        "d4c2d76",
        "1573471024",
        "fix",
        "contacts",
        "Abandon custom routereusestrategy"
    ],
    [
        "f220966",
        "1573466759",
        "fix",
        "calendar",
        "Fix linter errors"
    ],
    [
        "ab161a2",
        "1573466443",
        "fix",
        "account-app",
        "const-ize a variable to make linter happy"
    ],
    [
        "f9d6f52",
        "1573465246",
        "fix",
        "payments",
        "Make the shopping cart more resilient"
    ],
    [
        "7e3251e",
        "1573230634",
        "fix",
        "account-app",
        "Fix total price in shopping cart"
    ],
    [
        "be5c796",
        "1573229944",
        "feat",
        "account-app",
        "Add loading indicators to async elements of account-app"
    ],
    [
        "93bb314",
        "1573211390",
        "test",
        "rmmapi",
        "remove obsolete test assumptions"
    ],
    [
        "18dc94d",
        "1573023063",
        "fix",
        "dkim",
        "the button \"check cname\" now should display for all users"
    ],
    [
        "3ea1b7b",
        "1573012695",
        "feat",
        "README.md",
        "link the Github documentation to tips & tricks page"
    ],
    [
        "4ddb4cd",
        "1572627548",
        "feat",
        "calendar",
        "Make calendar (more) usable on mobile"
    ],
    [
        "e8c518a",
        "1572627548",
        "feat",
        "calendar",
        "allow expanding days from non-current month"
    ],
    [
        "c02d5cd",
        "1572627548",
        "refactor",
        "sidemenu",
        "refactor the sidemenu into its own component"
    ],
    [
        "f2ce8f4",
        "1572627011",
        "refactor",
        "app",
        "extract the mobileQuery into a service"
    ],
    [
        "eb33e58",
        "1572539144",
        "fix",
        "draftdesk",
        "Make sure draft previews don't overflow regardless of when they're created"
    ],
    [
        "04beb7e",
        "1572526335",
        "fix",
        "folderlist",
        "Make sure folders appear in the right order"
    ],
    [
        "81c901b",
        "1572454751",
        "fix",
        "dkim",
        "remove reconfigure option"
    ],
    [
        "f6a56f0",
        "1572451388",
        "fix",
        "httpinterceptor",
        "undo changes in httpinterceptor"
    ],
    [
        "94af34a",
        "1572442577",
        "fix",
        "calendar",
        "make sure toggling calendar visibility refreshes the event list"
    ],
    [
        "68a6efe",
        "1572426602",
        "feat",
        "calendar",
        "Make \"Synchronize calendars\" button more aggresive"
    ],
    [
        "c60113e",
        "1572368558",
        "feat",
        "calendar",
        "Add an activity tracker to monitor calendar queries"
    ],
    [
        "7987e25",
        "1572362180",
        "fix",
        "calendar",
        "refactor/fix the way event times are handled"
    ],
    [
        "164b9c2",
        "1572357709",
        "fix",
        "calendar",
        "don't double-encode calendar cache"
    ],
    [
        "a2242bf",
        "1572356855",
        "fix",
        "calendar",
        "fix changing event from one recurring freq to another"
    ],
    [
        "21e3cb7",
        "1572355885",
        "fix",
        "calendar",
        "fix recurring event settings"
    ],
    [
        "1a21270",
        "1572351944",
        "fix",
        "webmail",
        "don't keep the message pane open when in mobile view"
    ],
    [
        "d2969db",
        "1572351280",
        "style",
        "webmail",
        "adjust preview pane wording"
    ],
    [
        "9c4e9b6",
        "1572280164",
        "fix",
        "webmail",
        "Display viewMode menu even when no local index exists"
    ],
    [
        "5a30155",
        "1572279479",
        "feat",
        "webmail",
        "add an option to toggle the message pane openness"
    ],
    [
        "09a3fa1",
        "1572277440",
        "feat",
        "webmail",
        "Add an option to hide the message pane"
    ],
    [
        "0a51680",
        "1572269645",
        "fix",
        "login",
        "Make sure we're displaying all login errors"
    ],
    [
        "cbb5822",
        "1572268445",
        "test",
        "all",
        "make sure *all* tests are running again"
    ],
    [
        "716277f",
        "1572260992",
        "feat",
        "calendar",
        "add a settings option to clear the local cache"
    ],
    [
        "90cf8d5",
        "1571851107",
        "fix",
        "canvastable",
        "scroll lagging caused by focus"
    ],
    [
        "62ba9ba",
        "1571542164",
        "fix",
        "canvastable",
        "scroll speed, column resize"
    ],
    [
        "dbed608",
        "1571328720",
        "fix",
        "dkim",
        "fix lint errors"
    ],
    [
        "567a6b9",
        "1571325831",
        "style",
        "draftdesk",
        "Add a message to an empty draftdesk"
    ],
    [
        "405a10d",
        "1571325031",
        "fix",
        "calendar",
        "make sure allDay settings are respected"
    ],
    [
        "47bbc7d",
        "1571323867",
        "fix",
        "calendar",
        "prevent calendar visibility from being reset each update"
    ],
    [
        "906d570",
        "1571320989",
        "feat",
        "calendar",
        "Set a default calendar when creating new events"
    ],
    [
        "11b0c34",
        "1571320812",
        "style",
        "calendar",
        "order available calendars alphabetically"
    ],
    [
        "7ff74b7",
        "1571315487",
        "test",
        "all",
        "make sure all tests are running again"
    ],
    [
        "0bb45a3",
        "1571313210",
        "test",
        "e2e",
        "Add basic tests for calendar event creation"
    ],
    [
        "f9b179e",
        "1571290280",
        "fix",
        "dkim",
        "remove cname reconfigure functionality"
    ],
    [
        "4c62549",
        "1571290230",
        "feat",
        "dkim",
        "button to re-check cname in dkim page"
    ],
    [
        "51fb2f9",
        "1571244983",
        "fix",
        "account-app",
        "Implement the missing bits of PaymentRequest handling"
    ],
    [
        "16bd505",
        "1571244548",
        "fix",
        "email-app",
        "Hide the message panel when in compose/drafts"
    ],
    [
        "033f1f7",
        "1571243828",
        "fix",
        "calendar",
        "update event editor for the new API"
    ],
    [
        "54ea906",
        "1571149663",
        "feat",
        "calendar",
        "Implement client-side ical parsing"
    ],
    [
        "e124032",
        "1571063181",
        "test",
        "e2e",
        "extra compose test and root folder creation"
    ],
    [
        "64ace43",
        "1570810524",
        "feat",
        "compose",
        "Attachment upload progress bar indicate filename and filesize."
    ],
    [
        "765c319",
        "1570378912",
        "fix",
        "app",
        "re-add deprecated mobileQuery APIs"
    ],
    [
        "c42c1d6",
        "1570127201",
        "feat",
        "dkim",
        "create button to re-check dkim cnames"
    ],
    [
        "40130d2",
        "1570014789",
        "feat",
        "contacts-app",
        "Keep an offline cache of contacts"
    ],
    [
        "7c77048",
        "1569525279",
        "fix",
        "calendar",
        "Allow to move events between calendars by modifying them"
    ],
    [
        "b9fbfcb",
        "1569504496",
        "build",
        "material",
        "Update to angular/material 8"
    ],
    [
        "7dbfce2",
        "1569497862",
        "build",
        "calendar",
        "Update angular-calendar"
    ],
    [
        "87f5655",
        "1569497228",
        "refactor",
        "compose",
        "Use the native serviceworker bypass feature"
    ],
    [
        "8e4faa7",
        "1569425926",
        "build",
        "app",
        "Update to Angular 8, including required API changes"
    ],
    [
        "2c9d869",
        "1569425925",
        "refactor",
        "progress-service",
        "remove deprecated usage of BrowserXHR"
    ],
    [
        "a8233a3",
        "1569425925",
        "refactor",
        "mailviewer",
        "remove unnecessary use of HttpModule"
    ],
    [
        "15f93cb",
        "1569425925",
        "refactor",
        "searchservice",
        "remove a deprecated use of Injector.get"
    ],
    [
        "4670c0a",
        "1569425925",
        "refactor",
        "webmail",
        "remove deprecated MediaQueryList APIs"
    ],
    [
        "5e3cf47",
        "1569425925",
        "refactor",
        "canvastable",
        "migrate to non-deprecated APIs"
    ],
    [
        "8145736",
        "1569425925",
        "refactor",
        "all",
        "Remove most deprecated usage of '@angular/http'"
    ],
    [
        "fc4205c",
        "1569336615",
        "fix",
        "tests",
        "Update the commit log test, hopefully for the last time"
    ],
    [
        "330b926",
        "1567685774",
        "fix",
        "folder",
        "make sure folders are handled correctly regadless of order"
    ]
];
// END:AUTOGENERATED

export const changelog: ChangelogEntry[] = changes.map(entry => {
    const type = typeMapping[entry[2]];
    if (type === undefined) {
        throw new Error('Invalid change type in ' + entry);
    }
    return new ChangelogEntry(
        entry[0], parseInt(entry[1], 10), type, entry[3], entry[4]
    );
});
