// --------- BEGIN RUNBOX LICENSE ---------
// Copyright (C) 2016-2019 Runbox Solutions AS (runbox.com).
//
// This file is part of Runbox 7.
//
// Runbox 7 is free software: You can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// Runbox 7 is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Runbox 7. If not, see <https://www.gnu.org/licenses/>.
// ---------- END RUNBOX LICENSE ----------

import moment from 'moment';

export enum EntryType {
    BUILD,
    CI,
    DOCS,
    FEAT,
    FIX,
    PERF,
    REFACTOR,
    STYLE,
    TEST
}

const typeMapping = {
    'build':    EntryType.BUILD,
    'ci':       EntryType.CI,
    'docs':     EntryType.DOCS,
    'feat':     EntryType.FEAT,
    'feature':  EntryType.FEAT,
    'fix':      EntryType.FIX,
    'perf':     EntryType.PERF,
    'refactor': EntryType.REFACTOR,
    'style':    EntryType.STYLE,
    'test':     EntryType.TEST,
    // known typos
    'refator':  EntryType.REFACTOR,
};

export class ChangelogEntry {
    public datetime: moment.Moment;

    constructor(
        public hash:        string,
        public epoch:       number,
        public type:        EntryType,
        public component:   string,
        public description: string,
    ) {
        this.datetime = moment(this.epoch * 1000); // in ms
    }

    get url(): string {
        return `https://github.com/runbox/runbox7/commit/${this.hash}`;
    }
}


// These entries are auto-generated from build-changelog.js.
// Manual edits will be overwritten.
/* eslint-disable @typescript-eslint/quotes */
// BEGIN:AUTOGENERATED
const changes = [];
// END:AUTOGENERATED

export const changelog: ChangelogEntry[] = changes.map(entry => {
    const type = typeMapping[entry[2]];
    if (type === undefined) {
        throw new Error(`Invalid change type "${entry[2]}" in ${entry}`);
    }
    return new ChangelogEntry(
        entry[0], parseInt(entry[1], 10), type, entry[3], entry[4]
    );
});
