name: Commitlint

on:
  pull_request:
    branches: [master]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Lint commit messages
        run: |
          set -ue
          BASE=$(git merge-base origin/${{ github.event.pull_request.base.ref }} HEAD)
          echo "Linting commits from $BASE to HEAD"
          ! git log --no-merges --pretty=format:'%s' $BASE..HEAD | grep -vP '^(build|feat|refactor|fix)\([\w-]+\): '
